- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: hopeful-sound-326712
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ../hopeful-sound-326712-793154e35200.json
      zone: "europe-west3-c"
      region: "europe-west3"
  tasks:
   - set_fact:
         random_vm_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-{{ random_vm_name }}'
         size_gb: 20
         source_image: 'projects/centos-cloud/global/images/family/centos-8'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: 'address-{{ random_vm_name }}'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: vm-{{ random_vm_name }}
         machine_type: e2-medium
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         tags: 
            items: 'http-server,https-server'
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance


   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Copy host address to file 
     ansible.builtin.copy: 
        content: '{{ address.address }}' 
        dest: ./hosts 
   
   - name: Include role for the server
     include_role:
        name: '{{ role_name }}'