- name: Register Gitlab Runner
  hosts: localhost
  gather_facts: no
  vars:
      ssh_key_location: /home/bach/.ssh/id_rsa
      ssh_user: bahadir.tasdelen
      token: Vm-myUj74nVdvs_6ZEFS
      server_file: ./gitlab-server
      runner_file: ./gitlab-runner
  tasks:
   - name: Get Gitlab server address
     ansible.builtin.command:
          cmd: cat {{ server_file }}
     register: gitlab_server_address
   - name: Get Gitlab runner address
     ansible.builtin.command:
          cmd: cat {{ runner_file }}
     register: gitlab_runner_address
   - name: Create registration script
     ansible.builtin.copy: 
        content: 'gitlab-runner register --url "http://{{ gitlab_server_address.stdout }}/" --registration-token {{ token }} --description "$HOSTNAME"  --executor "shell" --non-interactive' 
        dest: ./register.sh
   - name: Make the script executable
     ansible.builtin.file:
        path: ./register.sh
        state: touch
        mode: u+x,g+x
   - name: Copy script to runner server
     ansible.builtin.command:
          cmd: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_location }} ./register.sh {{ ssh_user }}@{{ gitlab_runner_address.stdout }}:/tmp
   - name: Run the script
     ansible.builtin.command:
          cmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_location }} {{ ssh_user }}@{{ gitlab_runner_address.stdout }} 'sudo /tmp/register.sh'